#zamiast generatora użyłem wyrażenia generującego:
miesiace=(m for m in ["styczeń","luty","marzec","kwiecień","maj","czerwiec","lipec","sierpień","wrzesień","październik","listopad","grudzień"])
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))